

export const AppTypes = {
    ADD_TODO: `ADD_TODD`,
    ADD_TODO_FULFILLED: `ADD_TODD_FULFILLED`,
    ADD_TODO_ERROR: `ADD_TODD_ERROR`,

    UPDATE_TODO: `UPDATE_TODO`,
    UPDATE_TODO_FULFILLED: `UPDATE_TODO_FULFILLED`,
    UPDATE_TODO_ERROR: `UPDATE_TODO_ERROR`,

    GET_TODO: `GET_TODO`,
    GET_TODO_FULFILLED: `GET_TODO_FULFILLED`,
    GET_TODO_ERROR: `GET_TODO_ERROR`,

    DELETE_TODO: `DELETE_TODO`,
    DELETE_TODO_FULFILLED: `DELETE_TODO_FULFILLED`,
    DELETE_TODO_ERROR: `DELETE_TODO_ERROR`,
};
