

export const AppTypes = {

    ADD_TODO: `ADD_TODD`,
    ADD_TODO_FULFILLED: `ADD_TODD_FULFILLED`,
    ADD_TODO_ERROR: `ADD_TODD_ERROR`,

    UPDATE_TODO: `UPDATE_TODO`,
    UPDATE_TODO_FULFILLED: `UPDATE_TODO_FULFILLED`,
    UPDATE_TODO_ERROR: `UPDATE_TODO_ERROR`,

    GET_TODO: `GET_TODO`,
    GET_TODO_FULFILLED: `GET_TODO_FULFILLED`,
    GET_TODO_ERROR: `GET_TODO_ERROR`,

    DELETE_TODO: `DELETE_TODO`,
    DELETE_TODO_FULFILLED: `DELETE_TODO_FULFILLED`,
    DELETE_TODO_ERROR: `DELETE_TODO_ERROR`,

    SET_SELECTED_LIST: `SET_SELECTED_LIST`,
    GET_LIST_FULFILLED: `GET_LIST_FULFILLED`,

    ADD_LIST: `ADD_LIST`,
    DELETE_LIST: `DELETE_LIST`,
    UPDATE_LIST: `UPDATE_LIST`,


    UPDATE_FILTER: `UPDATE_FILTER`,
    UPDATE_LIST_FILTER: `UPDATE_LIST_FILTER`,
    SHOW_ALL: `SHOW_ALL`,
    SHOW_PENDING: `SHOW_PENDING`,
    UPDATE_TODO_STATUS: `UPDATE_TODO_STATUS`,

};
